apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3-exporter.fullname" . }}-secret
  labels:
    {{- include "s3-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ""  # Base64 encoded
  AWS_SECRET_ACCESS_KEY: ""  # Base64 encoded