apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "s3-exporter.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "s3-exporter.name" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  aws-region: {{ .Values.aws.region }}
  bucket-configs: |-
{{ .Values.exporter.bucketConfigs | toPrettyJson | indent 4 }}
  check-interval: "{{ .Values.exporter.checkInterval }}"
  port: "{{ .Values.exporter.port }}"