apiVersion: v1
kind: Service
metadata:
  name: {{ include "s3-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "s3-exporter.name" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "s3-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.exporter.port }}
    name: metrics
  type: {{ .Values.service.type }}